### PR TITLE
Lighthouse slasher

### PR DESCRIPTION
**Pull request by gbayasgalan**

### CODE REVIEW

**Review by stefa2k — COMMENTED** [review]
How is the env var `SLASHERDIR` that's used here https://github.com/stereum-dev/ethereum2-docker-build/blob/main/lighthouse/start/beacon.sh#L16 set?

**Review by stefa2k — CHANGES_REQUESTED** [review]
lgtm, just one last thing: can you please adapt the README.md of multiclient setup too (adding slasher)? Because changing `config/lighthouse/beacon.env` also affects the lighthouse beacon on multiclient.

**Comment by gbayasgalan** [comment]
SLASHERDIR is set up in 

> How is the env var `SLASHERDIR` that's used here https://github.com/stereum-dev/ethereum2-docker-build/blob/main/lighthouse/start/beacon.sh#L16 set?

I didn't add it to Git, now it's in config/lighthouse/beacon.env

**Comment by gbayasgalan** [comment]
> lgtm, just one last thing: can you please adapt the README.md of multiclient setup too (adding slasher)? Because changing `config/lighthouse/beacon.env` also affects the lighthouse beacon on multiclient.



> lgtm, just one last thing: can you please adapt the README.md of multiclient setup too (adding slasher)? Because changing `config/lighthouse/beacon.env` also affects the lighthouse beacon on multiclient.

yeah, sure. I think we should also add slasher in docker-compose.yaml?

**Review by stefa2k — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
